[book]
src = "src"
title = ""

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
mathjax-support = true
git-repository-url = "https://github.com/DappScout/LotteryProtocol"\\
theme = "navy"
default-theme = "navy"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
